module.exports = {
  "citation": require("./citation"),
  "cover": require("./cover"),
  "figure": require("./figure"),
  "caption": require("./caption"),
  "attrib": require("./attrib"),
  "formula": require("./formula"),
  "html_table": require("./html_table"),
  "table": require("./table"),
  "colgroup": require("./colgroup"),
  "thead": require("./thead"),
  "tbody": require("./tbody"),
  "tr": require("./tr"),
  "td": require("./td"),
  "th": require("./th"),
  "node": require("./node"),
  "composite": require("./composite"),
  "table_wrap_foot": require("./table_wrap_foot"),
  "footnote_reference": require("./footnote_reference"),
  "annotation": require("./annotation")
};